DROP TABLE USER_ROlES;
DROP TABLE USER_BEHAVIOR;
DROP TABLE USERS;
DROP TABLE BEHAVIORS;
DROP TABLE ROlES;

CREATE TABLE USERS (
    ID 				SERIAL PRIMARY KEY,
    USERNAME        CHARACTER VARYING(255) NOT NULL UNIQUE,
    EMAIL           CHARACTER VARYING(255) NOT NULL,
    PASSWORD        CHARACTER VARYING(255) NOT NULL,
    STATUS          BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE ROlES (
    ID 				SERIAL PRIMARY KEY,
    NAME        	CHARACTER VARYING(255) NOT NULL UNIQUE
);
CREATE TABLE USER_ROlES (
    USER_ID 		SERIAL,
	ROLE_ID 		SERIAL,
	PRIMARY KEY(USER_ID, ROLE_ID)
);
ALTER TABLE USER_ROlES
    ADD CONSTRAINT FK_USER_ROlE_USERS FOREIGN KEY ( USER_ID )
        REFERENCES USERS ( ID );

ALTER TABLE USER_ROlES
    ADD CONSTRAINT FK_USER_ROlE_ROLES FOREIGN KEY ( ROLE_ID )
        REFERENCES ROlES ( ID );

CREATE TABLE BEHAVIORS (
    ID  			SERIAL PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL
);

CREATE TABLE USER_BEHAVIOR (
    ID  			SERIAL PRIMARY KEY,
    USER_ID         INTEGER NOT NULL,
    BEHAVIOR_ID     INTEGER NOT NULL
);

ALTER TABLE USER_BEHAVIOR
    ADD CONSTRAINT FK_USER_BEHAVIOR_USERS FOREIGN KEY ( USER_ID )
        REFERENCES USERS ( ID );

ALTER TABLE USER_BEHAVIOR
    ADD CONSTRAINT FK_USER_BEHAVIOR_BEHAVIOR FOREIGN KEY ( BEHAVIOR_ID )
        REFERENCES BEHAVIORS ( ID );
		
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_USER');
	