DROP TABLE USER_ROlE;
DROP TABLE USER_BEHAVIOR;
DROP TABLE REGISTER_VERIFY
DROP TABLE USERS;
DROP TABLE BEHAVIORS;
DROP TABLE ROlES;


CREATE TABLE USERS (
    ID 				SERIAL PRIMARY KEY,
    USERNAME        CHARACTER VARYING(255) NOT NULL UNIQUE,
    EMAIL           CHARACTER VARYING(255) NOT NULL UNIQUE,
    PASSWORD        CHARACTER VARYING(255) NOT NULL,
    STATUS          BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE ROlES (
    ID 				SERIAL PRIMARY KEY,
    NAME        	CHARACTER VARYING(255) NOT NULL UNIQUE
);
CREATE TABLE USER_ROlE (
    USER_ID 		SERIAL,
	ROLE_ID 		SERIAL,
	PRIMARY KEY(USER_ID, ROLE_ID)
);
CREATE TABLE BEHAVIORS (
    ID  			SERIAL PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE USER_BEHAVIOR (
    ID  			SERIAL PRIMARY KEY,
    USER_ID         INTEGER NOT NULL,
    BEHAVIOR_ID     INTEGER NOT NULL
);
CREATE TABLE REGISTER_VERIFY (
    ID  			SERIAL PRIMARY KEY,
    USER_ID         INTEGER NOT NULL UNIQUE,
    TOKEN        	VARCHAR(255) NOT NULL UNIQUE,
	STATUS          BOOLEAN NOT NULL DEFAULT FALSE,
	DATE_EXPIED 	TIMESTAMP
);

ALTER TABLE USER_ROlE
    ADD CONSTRAINT FK_USER_ROlE_USERS FOREIGN KEY ( USER_ID )
        REFERENCES USERS ( ID );

ALTER TABLE USER_ROlE
    ADD CONSTRAINT FK_USER_ROlE_ROLES FOREIGN KEY ( ROLE_ID )
        REFERENCES ROlES ( ID );
		
ALTER TABLE USER_BEHAVIOR
    ADD CONSTRAINT FK_USER_BEHAVIOR_USERS FOREIGN KEY ( USER_ID )
        REFERENCES USERS ( ID );

ALTER TABLE USER_BEHAVIOR
    ADD CONSTRAINT FK_USER_BEHAVIOR_BEHAVIOR FOREIGN KEY ( BEHAVIOR_ID )
        REFERENCES BEHAVIORS ( ID );
		
ALTER TABLE REGISTER_VERIFY
    ADD CONSTRAINT FK_REGISTER_VERIFY_USER FOREIGN KEY ( USER_ID )
        REFERENCES USERS ( ID );
		
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_USER');

INSERT INTO users(username, email, password)
VALUES('admin','admin@gmail.com','$2a$10$SDXbrlw3FSp9E43yxkmS1emzXrv65AHxwpdVk1DLfxEqq1OxcoaHm');

INSERT INTO user_role VALUES(1,1);